/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    guests: GuestAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    guests: Guest;
    photos: Photo;
    messages: Message;
    'quiz-questions': QuizQuestion;
    'quiz-answers': QuizAnswer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'quiz-questions': QuizQuestionsSelect<false> | QuizQuestionsSelect<true>;
    'quiz-answers': QuizAnswersSelect<false> | QuizAnswersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    event: Event;
  };
  globalsSelect: {
    event: EventSelect<false> | EventSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Guest;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface GuestAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Everyone invited. Each guest gets a personal invitation code: open a guest to copy their link, QR code or a ready-made message.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: number;
  name: string;
  /**
   * How many people this invitation covers.
   */
  partySize: number;
  /**
   * e.g. “Table 4”. Guests only see this once seating is published.
   */
  tableLabel?: string | null;
  /**
   * Only tagged guests can play the quiz, and only while it’s switched Live.
   */
  unlocked?: boolean | null;
  rsvp?: ('pending' | 'yes' | 'no') | null;
  rsvpCount?: number | null;
  meal?: string | null;
  note?: string | null;
  /**
   * Created automatically. Change it to issue a new login; the old link stops working.
   */
  code?: string | null;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'guests';
}
/**
 * Photos shared by guests (and by you). Delete anything you don’t want on the wall.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  caption?: string | null;
  author?: string | null;
  /**
   * Set automatically from who uploaded it.
   */
  owner?: (number | null) | Guest;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  body: string;
  private?: boolean | null;
  author?: string | null;
  owner?: (number | null) | Guest;
  updatedAt: string;
  createdAt: string;
}
/**
 * Switch the quiz on under Globals → Wedding → “Access & games”, and tag guests under Guests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions".
 */
export interface QuizQuestion {
  id: number;
  question: string;
  /**
   * Add 2–4 answers and tick exactly one as correct.
   */
  options: {
    text: string;
    isCorrect?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Delete rows here to reset scores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-answers".
 */
export interface QuizAnswer {
  id: number;
  guest: number | Guest;
  question: number | QuizQuestion;
  choice: number;
  correct?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'guests';
        value: number | Guest;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'quiz-questions';
        value: number | QuizQuestion;
      } | null)
    | ({
        relationTo: 'quiz-answers';
        value: number | QuizAnswer;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'guests';
        value: number | Guest;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'guests';
        value: number | Guest;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  name?: T;
  partySize?: T;
  tableLabel?: T;
  unlocked?: T;
  rsvp?: T;
  rsvpCount?: T;
  meal?: T;
  note?: T;
  code?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  caption?: T;
  author?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  body?: T;
  private?: T;
  author?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions_select".
 */
export interface QuizQuestionsSelect<T extends boolean = true> {
  question?: T;
  options?:
    | T
    | {
        text?: T;
        isCorrect?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-answers_select".
 */
export interface QuizAnswersSelect<T extends boolean = true> {
  guest?: T;
  question?: T;
  choice?: T;
  correct?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event".
 */
export interface Event {
  id: number;
  /**
   * ON: anyone with the link can view every page, no code needed. They can still only add photos or messages, RSVP and play the quiz with a personal code. OFF: the invitation stays sealed until a code is entered.
   */
  openAccess?: boolean | null;
  quizStatus?: ('off' | 'live' | 'ended') | null;
  /**
   * Assign tables under Guests first.
   */
  seatingPublished?: boolean | null;
  partner1: string;
  partner2: string;
  /**
   * Format: 2027-05-15
   */
  date: string;
  /**
   * 24-hour, e.g. 16:00
   */
  time: string;
  note?: string | null;
  venue?: string | null;
  address?: string | null;
  mapUrl?: string | null;
  dressCode?: string | null;
  dressNote?: string | null;
  swatches?:
    | {
        /**
         * Hex colour, e.g. #1E3B2E
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  schedule?:
    | {
        /**
         * 24-hour, e.g. 16:00
         */
        time?: string | null;
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Format: 2027-04-15
   */
  rsvpDeadline?: string | null;
  mealOptions?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_select".
 */
export interface EventSelect<T extends boolean = true> {
  openAccess?: T;
  quizStatus?: T;
  seatingPublished?: T;
  partner1?: T;
  partner2?: T;
  date?: T;
  time?: T;
  note?: T;
  venue?: T;
  address?: T;
  mapUrl?: T;
  dressCode?: T;
  dressNote?: T;
  swatches?:
    | T
    | {
        color?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        time?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  rsvpDeadline?: T;
  mealOptions?:
    | T
    | {
        option?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}